### ISSUE TITLE
Korjaa lisätietojen linkit

### ISSUE THREAD

**Issue by AnnukkaV** [6aika/api-linked-events#6]
Korjaa lisätietojen linkit (Lisätietoa / further information:

Linked events: tapahtumarajapinnan toiminnot ja käyttötarkoitus
Linked events: rajapinnan tekniset vaatimukset).

Oikeat linkit: 
www.databusiness.fi/fi/avoindata/avoimet-rajapinnat/linkedevents-teknisetvaatimukset
www.databusiness.fi/fi/linked-events

**Comment by aapris** [comment]
Korjattu
